"""
Django settings for MeetClone project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = 'django-insecure-_w25bj6b(3o_dn-1*6j^qo05j6uk!sacn7v$+o-4dw=!qm6q2l'

DEBUG = True

ALLOWED_HOSTS = []


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # -----------------------------------------------------
    # Django
    # -----------------------------------------------------
    
     'daphne',


    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',


    # -----------------------------------------------------
    # Third-party
    # -----------------------------------------------------

    'channels',


    # -----------------------------------------------------
    # Project Apps
    # -----------------------------------------------------

    'accounts',

    'meetings',
    'notifications',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'MeetClone.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {

        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# =========================================================
# WSGI / ASGI
# =========================================================

WSGI_APPLICATION = (
    'MeetClone.wsgi.application'
)


ASGI_APPLICATION = (
    'MeetClone.asgi.application'
)


# =========================================================
# DATABASE
# =========================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',

    }

}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True


USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'

MEDIA_URL = '/media/'




MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# EMAIL
# DEVELOPMENT / TERMINAL ONLY
# =========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)


DEFAULT_FROM_EMAIL = (
    'noreply@meetclone.local'
)


# =========================================================
# LOGIN
# =========================================================

LOGIN_URL = '/accounts/login/'


# =========================================================
# CHANNEL LAYERS
# DEVELOPMENT
# =========================================================

CHANNEL_LAYERS = {

    'default': {

        'BACKEND':
            'channels.layers.InMemoryChannelLayer',

    },

}


# =====================================================
# SESSION SETTINGS
# =====================================================

# Browser close hone par user ko dobara login karna padega
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Optional: 1 hour session expiry
SESSION_COOKIE_AGE = 3600