# Generated by Django 6.0 on 2026-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People you follow'), ('private', 'Only me')], default='everyone', max_length=20),
        ),
    ]
