# Generated by Django 6.0 on 2026-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People you follow'), ('no_one', 'No one')], default='everyone', max_length=20),
        ),
    ]
