# Generated by Django 6.0 on 2026-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_message_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_activity_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meeting_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
